name: Download and Extract BSD Brawl APK

on:
  workflow_dispatch:

jobs:
  download-and-extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Apktool
        run: |
          wget https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.9.3.jar -O apktool.jar
          sudo mv apktool.jar /usr/local/bin/apktool.jar
          echo '#!/bin/bash' > /usr/local/bin/apktool
          echo 'java -jar /usr/local/bin/apktool.jar "$@"' >> /usr/local/bin/apktool
          sudo chmod +x /usr/local/bin/apktool

      - name: Download APK
        run: |
          wget "https://dl.bsdbrawl.net/file/bsd_brawl_v60.448_(29_2).apk" -O bsd_brawl_v60.apk

      - name: Extract APK
        run: |
          apktool d bsd_brawl_v60.apk -o extracted -f

      - name: Zip Extracted Files
        run: |
          zip -r extracted.zip extracted

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v60.448
          files: |
            bsd_brawl_v60.apk
            extracted.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
