name: Process Uploaded BSD Brawl APK

on:
  workflow_dispatch:

jobs:
  process-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Tools
        run: |
          wget https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.9.3.jar -O apktool.jar
          sudo mv apktool.jar /usr/local/bin/apktool.jar
          echo '#!/bin/bash' > /usr/local/bin/apktool
          echo 'java -jar /usr/local/bin/apktool.jar "$@"' >> /usr/local/bin/apktool
          sudo chmod +x /usr/local/bin/apktool
          sudo apt-get install -y zip

      - name: Download APK from Release
        run: |
          # Simplified for public access; token optional since repo is public
          curl -L "https://github.com/hustlersacademy/BrawlStarsMod/releases/download/v60.448/bsd_brawl_v60.448_.29_2.apk" -o bsd_brawl_v60.apk

      - name: Extract APK
        run: |
          apktool d bsd_brawl_v60.apk -o extracted -f

      - name: Check for Files Exceeding 100 MB
        run: |
          echo "Checking for files larger than 100 MB..."
          if find extracted -type f -size +100M | grep .; then
            echo "Files exceeding 100 MB:"
            find extracted -type f -size +100M -exec ls -lh {} \;
          else
            echo "Perfect. No files exceeded the limit."
          fi

      - name: Commit Extracted Files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add extracted || echo "Some files may exceed size limit"
          git commit -m "Add extracted BSD Brawl v60 files" || echo "Commit failed, likely due to large files"
          git push || echo "Push failed, proceeding with zipping"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Zip Extracted Files
        run: |
          zip -r extracted.zip extracted

      - name: Create New Release with APK and ZIP
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v60.448-new  # New tag to avoid conflict with existing v60.448
          name: "BSD Brawl v60 with Extracted Files"  # Release title
          body: "New release containing the original APK and extracted ZIP"  # Description
          files: |
            bsd_brawl_v60.apk
            extracted.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
